language: python

python:
    - 2.7

install:
    - pip install coveralls

script:
    - coverage run testrunner.py

after_success:
    - coveralls --verbose

notifications:
    email:
        - genocidedragon@gmail.com
