#!/usr/bin/env python
# coding: utf-8

from unittest import TestCase


class OriginalTestCase(TestCase): # sample class name

    def setUp(self):

        pass

    def tearDown(self):

        pass

    def test_xx(self): # sample test func name

        pass
